- hosts: default
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
    nextcloud_database_host: localhost
    nextcloud_database_name: nextcloud
    nextcloud_database_user: nc_user
    nextcloud_database_password: c9ED89gkS4jbVSC3
    nextcloud_admin_user: default
    nextcloud_admin_password: secr3t
    nextcloud_webserver: false

  handlers:
    - name: restart apache2
      service:
        name: apache2
        state: restarted

    - name: restart nginx
      service:
        name: nginx
        state: restarted

    - name: restart php-fpm
      service:
        name: php7.2-fpm
        state: restarted

  tasks:
    - name: define default vars
      include_vars: defaults/main.yml

    - name: include main tasks
      include_tasks: tasks/main.yml
