- hosts: default
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
    nextcloud_install_method: local

  handlers:
    - name: restart apache2
      service:
        name: apache2
        state: restarted

  tasks:
    - name: define default vars
      include_vars: defaults/main.yml

    - name: include main tasks
      include_tasks: tasks/main.yml
