- hosts: default
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3

  handlers:
    - include_tasks: handlers/main.yml

  tasks:
    - name: define default vars
      include_vars: defaults/main.yml

    - name: include main tasks
      include_tasks: tasks/main.yml
