- hosts: default
  become: true

  handlers:
    - include_tasks: handlers/main.yml

  tasks:
    - name: define default vars
      include_vars: defaults/main.yml

    - name: include main tasks
      include_tasks: tasks/main.yml
