
- name: update and upgrade packages
  apt:
    update_cache: true
    upgrade: true
    cache_valid_time: 86400

- name: download nextcloud
  unarchive:
    src: https://download.nextcloud.com/server/releases/nextcloud-15.0.0.tar.bz2
    dest: "{{ web_dir }}"
    owner: "{{ web_user }}"
    group: "{{ web_group }}"
    mode: "u+rw,g+rw"
    remote_src: yes
  when: false

- name: make occ executable
  file:
    path: "{{ nextcloud_path }}/occ"
    mode: "u+x,g+x"

- name: execute maintenance:isntall via occ
  shell: "./occ maintenance:install --database pgsql --database-name {{ nextcloud_database_name }} --database-host {{ nextcloud_database_host }} --database-port {{ nextcloud_database_port }} --database-user {{ nextcloud_database_user }} --database-pass {{ nextcloud_database_password }} --admin-user {{ nextcloud_admin_user }} --admin-pass {{ nextcloud_admin_password }}"
  become: "{{ web_user }}"
  args:
    chdir: "{{ nextcloud_path }}"

- name: install required packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - php7.2
      - bzip2
      - libapache2-mod-php
      - php-gd
      - php-json
      - php-curl
      - php-mbstring
      - php-intl
      - php-imagick
      - php-xml
      - php-zip
      - python3-psycopg2

- name: install database
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - postgresql
      - php-pgsql

- name: add nextcloud database
  become: true
  become_user: postgres
  postgresql_db:
    name: "{{ nextcloud_database_name }}"

- name: add nextcloud role in posgresql
  become: true
  become_user: postgres
  postgresql_user:
    db: "{{ nextcloud_database_name }}"
    name: "{{ nextcloud_database_user }}"
    password: "{{ nextcloud_database_password }}"

- name: configure apache
  template:
    src: templates/apache-nextcloud.conf.j2
    dest: /etc/apache2/sites-available/nextcloud.conf
  notify: restart apache2

- name: enable nextcloud config
  shell: "a2ensite nextcloud"

