- name: update and upgrade packages
  apt:
    update_cache: true
    upgrade: true
    cache_valid_time: 86400

- name: check if apt-get requires a reboot
  command: test -f /var/run/reboot-required
  register: apt_get_requires_reboot
  ignore_errors: True

- include_tasks: web.yml

- include_tasks: php-fpm.yml

- include_tasks: database.yml
  when: nextcloud_database_remote == false

- name: install required packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - bzip2
      - php7.2
      - php-gd
      - php-json
      - php-curl
      - php-mbstring
      - php-intl
      - php-imagick
      - php-xml
      - php-zip

- name: check if installer is present locally
  become: no
  local_action: stat path="./files/nextcloud-15.0.0.tar.bz2"
  register: nextcloud_installer_present
  ignore_errors: true

- name: download nextcloud
  unarchive:
    src: https://download.nextcloud.com/server/releases/nextcloud-15.0.0.tar.bz2
    dest: "{{ web_dir }}"
    owner: "{{ web_user }}"
    group: "{{ web_group }}"
    mode: "u+rw,g+rw"
    remote_src: yes
  when: nextcloud_installer_present.stat.exists == false

- name: copy installer from host
  unarchive:
    src: files/nextcloud-15.0.0.tar.bz2
    dest: "{{ web_dir }}"
    owner: "{{ web_user }}"
    group: "{{ web_group }}"
    mode: "u+rw,g+rw"
    remote_src: no
  when: nextcloud_installer_present.stat.exists == true

- name: make occ executable
  file:
    path: "{{ nextcloud_path }}/occ"
    mode: "u+x,g+x"

- name: make config group readable
  file:
    path: "{{ nextcloud_path }}/config/"
    mode: "g+w"
    recurse: true

- name: check if already configured
  shell: "test -f {{ nextcloud_path }}/config/config.php"
  register: nextcloud_configured
  ignore_errors: true

- name: execute install script via occ
  shell: "./occ maintenance:install --database pgsql --database-name {{ nextcloud_database_name }} --database-host {{ nextcloud_database_host }} --database-port {{ nextcloud_database_port }} --database-user {{ nextcloud_database_user }} --database-pass {{ nextcloud_database_password }} --admin-user {{ nextcloud_admin_user }} --admin-pass {{ nextcloud_admin_password }} --data-dir {{ nextcloud_data_dir }}"
  become_user: "{{ web_user }}"
  args:
    chdir: "{{ nextcloud_path }}"
  when: nextcloud_configured is failure

- name: configure nextcloud pool
  template:
    src: templates/php-fpm.conf.j2
    dest: /etc/php/7.2/fpm/pool.d/nextcloud.conf
  notify: restart php-fpm

- name: delete www pool
  file:
    path: /etc/php/7.2/fpm/pool.d/www.conf
    state: absent
  notify: restart php-fpm

