- name: add web_user to group web_group
  user:
    name: "{{ web_user }}"
    group: "{{ web_group }}"
    append: yes

- name: make www dir
  file:
    path: "{{ web_dir }}"
    state: directory
    owner: "{{ web_user }}"
    group: "{{ web_group }}"
    recurse: true

- include_tasks: ./apache.yml
  when: false

- include_tasks: ./nginx.yml
  when: true
